### ISSUE TITLE
0 if fails

### ISSUE THREAD

**Issue by upost** [lpereira/finf#3]
I tried to work with finf and found it's great (see my fork where I added some words), but there's one issue I cannot fix.

try:
`0 if 1 . then`
This should do nothing, but it yields "Unimplemented opcode: xxx' and hangs up the system.
`1 if 1 . then` works as intended.

Yes I know that normally if then only works in a word definition, but in Finf this also crashes:

```
>>> : test 1 if 1 . then ;
>>> test
1>>> : test1 0 if 1 . then ;
>>> test1
Unimplemented opcode: 101
Unimplemented opcode: 116
Unimplemented opcode: 116
3588Unimplemented opcode: 186
Unimplemented opcode: 153
```
I suspect something could be wrong in open_scope() in the else branch:
```
if (program[entry].opcode == OP_IF) {
      if (stack_pop()) {
        entry = open_scope(entry + 1, program[program[entry].param].opcode);
      } 
      else {
        entry = open_scope(program[entry].param + 1, OP_THEN);
      }
    } 
```

any idea?

**Comment by lpereira** [comment]
I really don't know what could be going wrong. It's been many years since I've touched this code. I do appreciate patches fixing this, though.

**Comment by upost** [comment]
Yeah I had a feeling that this would be the answer. I'll try to sort it out!

**Comment by upost** [comment]
Got it. The +1 was wrong, as in this case we must continue at the goto destination and not one step further.
If you like to fix it, look into the commit in my fork:
https://github.com/upost/finf/commit/9c0c4e88444cf9c05b02a94dd5d1e6673438f6ac
I'm going to further improve FINF, as I like it very much for simple Arduino Development!
